name: main

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'mkdocs.yml'
      - 'docs/**'
      - 'catalog-info.yaml'


jobs:
  env:
    uses: analect-io/.github/.github/workflows/env.yaml@main

  promote:
    uses: analect-io/.github/.github/workflows/promote.yaml@main
    secrets: inherit
    with:
      tag: 
      repository: 
      url: https://.analect.com
      environment: production
    needs:
      - env

  notify:
    uses: analect-io/.github/.github/workflows/notify.yaml@main
    if: always()
    secrets: inherit
    needs:
      - promote
